### ISSUE TITLE
Implement simple delay

### ISSUE THREAD

**Issue by thomaschhh** [thomaschhh/Reverb#2]
As a first step, a simple delay is to be implemented.

**Comment by thomaschhh** [comment]
### Features to Be Implemented

- [x] volume decreases
- [x] no infinite feedback
- [x] works in stereo mode only (stereo → stereo)

**Comment by thomaschhh** [comment]
Added a simple delay @parednuw. 
Could you check this version? However, there is some distortion going on atm.

**Comment by parednuw** [comment]
@thomaschhh commented

**Comment by thomaschhh** [comment]
ef96da8 fixes the cracking. 
I think we can try to merge this with the CMake / main branch.

**Comment by parednuw** [comment]
@thomaschhh 68fa6f55f685f01f4c0688e7be6390aa8930cfb3 sounds good, let`s continue from here onwards with every new branch.
can you delete all other branches? they are not longer needed.

**Comment by thomaschhh** [comment]
Will do.

**Comment by thomaschhh** [comment]
Done.
