### ISSUE TITLE
Create CMake project for VSC

### ISSUE THREAD

**Issue by parednuw** [thomaschhh/Reverb#9]
We want to be able to build a Visual Studio Code project from CMake.

**Comment by parednuw** [comment]
@thomaschhh please check out my [commit](https://github.com/thomaschhh/Reverb/compare/main...create-cmakeproject-vsc). Let's see :D

**Comment by thomaschhh** [comment]
Great commit message 😆 

It's working on my side.

Two things maybe:
- I would separate different subject matters into individual commits (source code changes & CMake project setup) 
- We could add the functionality to automatically copy the plug-ins to the desired destination after build. What do you think? https://git.iem.at/audioplugins/IEMPluginSuite/-/blob/master/CMakeLists.txt might be a starting point.
